name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python Build for Windows(PyInstaller)
        uses: vednig/pyinstaller-action-windows@v0.1.5
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
